### ISSUE TITLE
Add backup server hostkey to known_hosts

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-backup#7]
Basically:

```yaml
- name: Get hostkey for backup server.
  set_fact:
    backup_hostkey: "{{ lookup('pipe', 'ssh-keyscan -t rsa backup.example.com') }}"

- name: Add backup server to known hosts.
  known_hosts:
    name: backup.example.com
    state: present
    key: "{{ backup_hostkey }}"
  become: yes
  become_user: "{{ backup_user }}"
```
